# **Introducción a Numpy**

**NumPy** (Numerical Python) es una librería fundamental para el cálculo científico en Python.  
Proporciona soporte para **arrays multidimensionales** y una amplia colección de funciones matemáticas de alto rendimiento.

## Características principales
- **Arrays (ndarray):** estructuras eficientes para almacenar y manipular datos numéricos.
- **Operaciones vectorizadas:** permiten cálculos rápidos sin necesidad de bucles explícitos.
- **Funciones matemáticas avanzadas:** trigonometría, álgebra lineal, estadísticas, transformadas de Fourier.
- **Manejo de datos multidimensionales:** matrices, tensores y operaciones sobre ellos.
- **Interoperabilidad:** se integra fácilmente con otras librerías como Pandas, Matplotlib y Scikit-learn.

## Ventajas
- Mucho más rápido y eficiente que las listas nativas de Python para cálculos numéricos.
- Sintaxis clara y concisa para operaciones matemáticas.
- Base sobre la que se construyen muchas librerías de ciencia de datos y aprendizaje automático.

NumPy es el **pilar del ecosistema científico en Python**, ofreciendo herramientas poderosas para trabajar con datos numéricos y realizar cálculos de manera eficiente.


---

# Funciones en NumPy (`np`)

NumPy es la librería base para cálculos numéricos en Python. Sus funciones se pueden agrupar en varias categorías:

## 1. Creación de arrays
- `np.array`, `np.zeros`, `np.ones`, `np.empty`
- `np.arange`, `np.linspace`, `np.logspace`
- `np.identity`, `np.eye`

## 2. Manipulación de arrays
- `reshape`, `ravel`, `flatten`
- `transpose`, `swapaxes`, `moveaxis`
- `concatenate`, `stack`, `split`, `tile`, `repeat`

## 3. Operaciones matemáticas
- Aritméticas: `add`, `subtract`, `multiply`, `divide`, `power`
- Trigonométricas: `sin`, `cos`, `tan`, `arcsin`, `arccos`
- Exponenciales y logarítmicas: `exp`, `log`, `log10`, `sqrt`

## 4. Estadísticas y agregaciones
- `mean`, `median`, `std`, `var`
- `min`, `max`, `sum`, `prod`
- `argmin`, `argmax`

## 5. Aleatoriedad (`np.random`)
- Distribuciones: `uniform`, `normal`, `binomial`, `poisson`, `exponential`, `beta`, `gamma`, `chisquare`, `lognormal`, `multinomial`, etc.
- Generación básica: `rand`, `randn`, `randint`, `choice`

## 6. Álgebra lineal (`np.linalg`)
- `dot`, `matmul`
- `inv`, `det`, `eig`, `svd`
- `norm`, `solve`

## 7. Funciones lógicas y comparación
- `greater`, `less`, `equal`, `not_equal`
- `logical_and`, `logical_or`, `logical_not`
- `where`, `any`, `all`

## 8. Funciones especiales
- `unique`, `sort`, `argsort`
- `clip`, `round`, `floor`, `ceil`
- `vectorize`, `fromfunction`

NumPy ofrece funciones para:
- **Crear y manipular arrays**
- **Realizar cálculos matemáticos y estadísticos**
- **Generar números aleatorios**
- **Resolver problemas de álgebra lineal**
- **Comparaciones y operaciones lógicas**

In [2]:
import pandas as pd
import numpy as np

# Distribuciones en `np.random` (NumPy)

El módulo `numpy.random` permite generar números aleatorios siguiendo distintas **distribuciones de probabilidad**.  
Estas funciones son muy útiles en simulaciones, estadística y machine learning.

## Distribuciones principales

### Uniforme
- **`np.random.uniform(low, high, size)`**
- Genera valores dentro de un rango `[low, high)` con igual probabilidad.

### Normal (Gaussiana)
- **`np.random.normal(loc, scale, size)`**
- Distribución de campana centrada en `loc` (media) con desviación estándar `scale`.

### Binomial
- **`np.random.binomial(n, p, size)`**
- Número de éxitos en `n` ensayos con probabilidad `p` de éxito.

### Poisson
- **`np.random.poisson(lam, size)`**
- Modela el número de eventos que ocurren en un intervalo dado con tasa `lam`.

### Exponencial
- **`np.random.exponential(scale, size)`**
- Tiempo entre eventos en un proceso de Poisson, con parámetro `scale`.

### Beta
- **`np.random.beta(a, b, size)`**
- Distribución continua en el rango `[0,1]`, usada en estadística bayesiana.

### Gamma
- **`np.random.gamma(shape, scale, size)`**
- Generalización de la exponencial, útil en tiempos de espera y colas.

### Chi-cuadrado
- **`np.random.chisquare(df, size)`**
- Distribución usada en pruebas de hipótesis, con `df` grados de libertad.

### Lognormal
- **`np.random.lognormal(mean, sigma, size)`**
- Valores positivos cuya log-transformación sigue una distribución normal.

### Geométrica
- **`np.random.geometric(p, size)`**
- Número de ensayos hasta el primer éxito con probabilidad `p`.

### Multinomial
- **`np.random.multinomial(n, pvals, size)`**
- Generalización de la binomial para múltiples categorías.

### F-distribution
- **`np.random.f(dfnum, dfden, size)`**
- Usada en pruebas de varianza y ANOVA.

Estas funciones son esenciales para **simulación estadística y modelado probabilístico** en Python.


In [ ]:
# Crear arreglos NumPy
# Desde lista
arr1 = np.array([1, 2, 3, 4, 5])

# Desde lista de listas (matriz)
arr2 = np.array([[1, 2], [3, 4]])

print(arr1)
print(arr2)

In [3]:
# Fijar semilla para reproducibilidad
np.random.seed(42)

# Número de registros simulados
n = 100

# Crear DataFrame simulado
df = pd.DataFrame({
    "Precio_Accion": np.random.uniform(50, 500, n),       # Precios de acciones entre 50 y 500
    "Volumen": np.random.randint(1000, 100000, n),        # Volumen de transacciones
    "Retorno": np.random.normal(0, 0.05, n),             # Retornos diarios, distribución normal
    "Riesgo": np.random.uniform(0.01, 0.3, n),           # Riesgo asociado a la acción
    "Dividendos": np.random.choice([0, 0.01, 0.02, 0.03], n),  # Dividendos posibles
    "Beta": np.random.uniform(0.5, 1.5, n),              # Beta del activo
    "Ratio_P_E": np.random.uniform(5, 40, n),            # Ratio Precio/Utilidad
    "Inflacion": np.random.normal(0.02, 0.01, n),        # Inflación diaria simulada
})

# Mostrar las primeras filas
print(df.head())

   Precio_Accion  Volumen   Retorno    Riesgo  Dividendos      Beta  \
0     218.543053    51015  0.004983  0.233298        0.00  1.486001   
1     477.821438    55268 -0.025174  0.072588        0.03  1.253378   
2     379.397274    88939 -0.077533  0.190638        0.00  0.876260   
3     319.396318    19141  0.003428  0.034751        0.02  0.583501   
4     120.208388    81356 -0.053115  0.024988        0.00  1.277147   

   Ratio_P_E  Inflacion  
0   8.974516   0.036871  
1  28.505062   0.028816  
2  23.210770   0.019920  
3  32.031144   0.034799  
4  23.205723   0.020774  


In [4]:
# -------------------------------
# Creación de arrays NumPy desde columnas del DataFrame
# -------------------------------

# Convertir columnas de DataFrame en arrays NumPy
# Esto permite aplicar operaciones vectorizadas, álgebra lineal y funciones matemáticas de manera eficiente
arr_precio = df["Precio_Accion"].to_numpy()  # Alternativa: np.array(df["Precio_Accion"])
arr_volumen = df["Volumen"].to_numpy()       # Mantener consistencia y eficiencia

# Verificar los primeros elementos para confirmar la conversión
print("Primeros 5 valores de Precio_Accion:", arr_precio[:5])
print("Primeros 5 valores de Volumen:", arr_volumen[:5])


Primeros 5 valores de Precio_Accion: [218.54305348 477.82143788 379.39727382 319.39631789 120.2083882 ]
Primeros 5 valores de Volumen: [51015 55268 88939 19141 81356]


In [ ]:
# -------------------------------
# Arrays especiales: ceros, unos y vacíos
# -------------------------------

# Array de ceros: útil para inicializar vectores o acumuladores
zeros_array = np.zeros(5)  # Crea un array de 5 elementos todos con valor 0
print("Array de ceros:", zeros_array)

# Array de unos: útil para inicializar multiplicadores o máscaras
ones_array = np.ones(5)    # Crea un array de 5 elementos todos con valor 1
print("Array de unos:", ones_array)

# Array vacío: crea un array sin inicializar (valores aleatorios de memoria)
# Útil cuando se va a rellenar inmediatamente con datos específicos
empty_array = np.empty(5)
print("Array vacío (valores no inicializados):", empty_array)

# Array con un valor específico
full = np.full((2,3), 7)      # [[7 7 7] [7 7 7]]
print("Array lleno con un valor específico:\n", full)

Array de ceros: [0. 0. 0. 0. 0.]
Array de unos: [1. 1. 1. 1. 1.]
Array vacío (valores no inicializados): [1. 1. 1. 1. 1.]


In [6]:
# -------------------------------
# Arrays con rangos
# -------------------------------

# np.arange(start, stop, step): crea un array con valores desde start hasta stop (excluido) con paso step
arange_array = np.arange(0, 50, 5)  # 0, 5, 10, ..., 45
print("Array con arange:", arange_array)

# np.linspace(start, stop, num): crea un array de 'num' valores igualmente espaciados entre start y stop (incluido)
linspace_array = np.linspace(0, 1, 5)  # 0.0, 0.25, 0.5, 0.75, 1.0
print("Array con linspace:", linspace_array)

# np.logspace(start, stop, num): crea un array de 'num' valores igualmente espaciados en escala logarítmica
# start y stop son exponentes de base 10 por defecto
logspace_array = np.logspace(0, 2, 5)  # 10^0, 10^0.5, 10^1, 10^1.5, 10^2
print("Array con logspace:", logspace_array)


Array con arange: [ 0  5 10 15 20 25 30 35 40 45]
Array con linspace: [0.   0.25 0.5  0.75 1.  ]
Array con logspace: [  1.           3.16227766  10.          31.6227766  100.        ]


In [ ]:
# -----------------------------------------
# Funciones matemáticas y operaciones con NumPy
# -----------------------------------------

# Convertimos la columna Precio_Accion a un arreglo NumPy
x = df["Precio_Accion"].values  

# Convertimos la columna Volumen a un arreglo NumPy
y = df["Volumen"].values       

# 1. Suma elemento a elemento (Precio_Accion + Volumen)
suma = np.add(x, y)           
df["Suma"] = suma              # Guardamos la suma en una nueva columna

# 2. Resta elemento a elemento (Precio_Accion - Volumen)
resta = np.subtract(x, y)     
df["Resta"] = resta            # Guardamos la resta en una nueva columna

# 3. Multiplicación elemento a elemento (Precio_Accion * Volumen)
producto = np.multiply(x, y)  
df["Producto"] = producto      # Guardamos el producto en una nueva columna

# 4. División elemento a elemento (Precio_Accion / Volumen)
division = np.divide(x, y)     
df["Division"] = division      # Guardamos la división en una nueva columna

# 5. Potencia (Precio_Accion elevado al cuadrado)
potencia = np.power(x, 2)      
df["Precio_Potencia2"] = potencia  # Guardamos la potencia en una nueva columna

# 6. Módulo (Volumen mod Precio_Accion)
# Calcula el resto de la división de cada elemento de a entre el correspondiente elemento de b.
mod = np.mod(y, x)             
df["Modulo"] = mod             # Guardamos el resultado del módulo en una nueva columna

# 7. Resto (remainder, similar a módulo pero con manejo distinto de negativos)
resto = np.remainder(y, x)    
df["Resto"] = resto            # Guardamos el resto en una nueva columna

# 8. División entera (floor divide, división redondeada hacia abajo)
div_entera = np.floor_divide(y, x)  
df["Div_Entera"] = div_entera  # Guardamos la división entera en una nueva columna

# Mostrar las primeras filas del DataFrame con todas las operaciones
print("\nDataFrame con operaciones NumPy:\n", df.head())


DataFrame con operaciones NumPy:
    Precio_Accion  Volumen   Retorno    Riesgo  Dividendos      Beta  \
0     218.543053    51015  0.004983  0.233298        0.00  1.486001   
1     477.821438    55268 -0.025174  0.072588        0.03  1.253378   
2     379.397274    88939 -0.077533  0.190638        0.00  0.876260   
3     319.396318    19141  0.003428  0.034751        0.02  0.583501   
4     120.208388    81356 -0.053115  0.024988        0.00  1.277147   

   Ratio_P_E  Inflacion          Suma         Resta      Producto  Division  \
0   8.974516   0.036871  51233.543053 -50796.456947  1.114897e+07  0.004284   
1  28.505062   0.028816  55745.821438 -54790.178562  2.640824e+07  0.008646   
2  23.210770   0.019920  89318.397274 -88559.602726  3.374321e+07  0.004266   
3  32.031144   0.034799  19460.396318 -18821.603682  6.113565e+06  0.016687   
4  23.205723   0.020774  81476.208388 -81235.791612  9.779674e+06  0.001478   

   Precio_Potencia2      Modulo       Resto  Div_Entera  
0    

In [34]:
# -----------------------------------------
# Funciones para encontrar índices de valores mínimos y máximos
# -----------------------------------------

# Convertir columna a array NumPy
precios = df["Precio_Accion"].values

# Índice del precio mínimo
idx_min = np.argmin(precios)
print("\nÍndice del precio mínimo:", idx_min)
print("Precio mínimo:", precios[idx_min])

# Índice del precio máximo
idx_max = np.argmax(precios)
print("\nÍndice del precio máximo:", idx_max)
print("Precio máximo:", precios[idx_max])


Índice del precio mínimo: 72
Precio mínimo: 52.48495270562108

Índice del precio máximo: 69
Precio máximo: 494.0991214702328


In [8]:
# -------------------------------
# Matrices identidad y diagonal
# -------------------------------

# np.identity(n): crea una matriz identidad cuadrada de tamaño n x n
# Matriz identidad: 1 en la diagonal principal y 0 en el resto
identity_matrix = np.identity(3)
print("Matriz identidad 3x3:\n", identity_matrix)

Matriz identidad 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# np.eye(N, M=None, k=0): crea una matriz con 1 en la diagonal k y 0 en el resto
# N: número de filas, M: número de columnas (opcional), k: desplazamiento de la diagonal
eye_matrix = np.eye(3, 4, k=1)  # 3 filas, 4 columnas, diagonal desplazada una posición hacia arriba
print("\nMatriz con diagonal desplazada k=1 (3x4):\n", eye_matrix)



Matriz con diagonal desplazada k=1 (3x4):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# -------------------------------
# Comparaciones
# -------------------------------
print("Comparaciones element-wise:")
print("Precio > 300:\n", np.greater(df["Precio_Accion"], 300).value_counts(), "\n")
print("Riesgo < 0.1:\n", np.less(df["Riesgo"], 0.1).value_counts(), "\n")
print("Dividendos == 0.02:\n", np.equal(df["Dividendos"], 0.02).value_counts(), "\n")
print("Retorno != 0:\n", np.not_equal(df["Retorno"], 0).value_counts(), "\n")

Comparaciones element-wise:
Precio > 300:
 Precio_Accion
False    59
True     41
Name: count, dtype: int64 

Riesgo < 0.1:
 Riesgo
False    68
True     32
Name: count, dtype: int64 

Dividendos == 0.02:
 Dividendos
False    74
True     26
Name: count, dtype: int64 

Retorno != 0:
 Retorno
True    100
Name: count, dtype: int64 



In [11]:
# -------------------------------
# Operaciones lógicas con NumPy
# -------------------------------

print("Operaciones lógicas:")

# Crear máscaras booleanas según condiciones financieras
# np.greater: devuelve True si el valor es mayor que el límite
alta_rentabilidad = np.greater(df["Retorno"], 0.02)  # Retorno > 2%

# np.less: devuelve True si el valor es menor que el límite
bajo_riesgo = np.less(df["Riesgo"], 0.1)  # Riesgo < 0.1

# np.logical_and: True si ambas condiciones se cumplen
print("Alta rentabilidad AND bajo riesgo:\n", np.logical_and(alta_rentabilidad, bajo_riesgo).value_counts(), "\n")

# np.logical_or: True si al menos una de las condiciones se cumple
print("Alta rentabilidad OR bajo riesgo:\n", np.logical_or(alta_rentabilidad, bajo_riesgo).value_counts(), "\n")

# np.logical_not: invierte los valores booleanos (True -> False, False -> True)
print("NOT bajo riesgo:\n", np.logical_not(bajo_riesgo).value_counts(), "\n")


Operaciones lógicas:
Alta rentabilidad AND bajo riesgo:
 False    84
True     16
Name: count, dtype: int64 

Alta rentabilidad OR bajo riesgo:
 True     54
False    46
Name: count, dtype: int64 

NOT bajo riesgo:
 Riesgo
True     68
False    32
Name: count, dtype: int64 



In [12]:
# -------------------------------
# Condicional con np.where
# -------------------------------
df["Clasificacion"] = np.where(
    np.logical_and(alta_rentabilidad, bajo_riesgo),
    "Premium",
    np.where(alta_rentabilidad, "Rentable", "Normal")
)
print("Clasificación de activos:\n", df[["Retorno", "Riesgo", "Clasificacion"]].head(), "\n")

print(df['Clasificacion'].value_counts())


Clasificación de activos:
     Retorno    Riesgo Clasificacion
0  0.004983  0.233298        Normal
1 -0.025174  0.072588        Normal
2 -0.077533  0.190638        Normal
3  0.003428  0.034751        Normal
4 -0.053115  0.024988        Normal 

Clasificacion
Normal      62
Rentable    22
Premium     16
Name: count, dtype: int64


In [13]:
# -------------------------------
# any y all
# -------------------------------
print("any y all:")
print("¿Algún activo con retorno > 0.04?", np.any(df["Retorno"] > 0.04))
print("¿Todos los activos tienen riesgo < 0.3?", np.all(df["Riesgo"] < 0.3))

any y all:
¿Algún activo con retorno > 0.04? True
¿Todos los activos tienen riesgo < 0.3? True


In [14]:
# -------------------------------
# Transformaciones de arrays: reshape, ravel, flatten
# -------------------------------

# - `reshape(filas, columnas)`: cambia la **forma** del array sin aplanarlo.  
# - `ravel()`: aplana el array en 1D y devuelve una **vista** (modificarlo puede afectar el original).  
# - `flatten()`: aplana el array en 1D y devuelve una **copia** (no afecta el original).

# Queremos reorganizar arr_precio en 10 filas
filas = 10
columnas = 10  # Para arr_precio de 100 elementos, columnas = 100/10 = 10

# -------------------------------
# Reshape: convierte un array 1D en una matriz 2D
# La nueva matriz tendrá 'filas' filas y 'columnas' columnas
# Debe coincidir el número total de elementos
reshaped = arr_precio.reshape(filas, columnas)
print("Array reshaped (10 filas x 10 columnas):\n", reshaped)

# -------------------------------
# Ravel: aplana la matriz en un array 1D
# Devuelve una **vista**, por lo que modificar raveled puede afectar arr_precio original
raveled = reshaped.ravel()
print("\nArray raveled (aplanado, vista 1D):\n", raveled)

# -------------------------------
# Flatten: aplana la matriz en un array 1D
# Devuelve una **copia**, por lo que modificar flattened no afecta arr_precio original
flattened = reshaped.flatten()
print("\nArray flattened (aplanado, copia):\n", flattened)


Array reshaped (10 filas x 10 columnas):
 [[218.54305348 477.82143788 379.39727382 319.39631789 120.2083882
  120.19753415  76.13762548 439.7792656  320.50175528 368.63266001]
 [ 59.26302243 486.45943347 424.59918836 145.55259981 131.82123524
  132.53202943 186.90900933 286.14039423 244.37525839 181.05311309]
 [325.33380263 112.77223729 181.46509184 214.86282948 255.2314929
  403.32918263 139.85320197 281.40549729 316.58655599  70.90268572]
 [323.39518336 126.73585566  79.27321684 476.99849176 484.53441488
  413.77880665 187.07619613  93.9524513  357.90486193 248.06862218]
 [104.91720568 272.82960955  65.4748345  459.19418094 166.45099172
  348.13502796 190.26998424 284.03060953 296.0196257  133.18450499]
 [486.31308249 398.80977051 472.7745237  452.67230769 319.05499046
  464.84340576  89.82162592 138.19228809  70.35228001 196.39864884]
 [224.90478036 172.1070643  422.93187912 210.53899701 176.42052936
  294.21323742 113.41590124 410.98864134  83.54778966 494.09912147]
 [397.51014618 

In [15]:
# -------------------------------
# Transpose, swapaxes, moveaxis (mejorado)
# -------------------------------

# Crear matriz 2D con precios y volúmenes
matrix_2d = np.array([arr_precio, arr_volumen])
print("Matriz 2D original (2 filas x 10 columnas):\n", matrix_2d, "\n")

# Transpuesta: filas ↔ columnas
transposed = matrix_2d.T
print("Transpuesta (10 filas x 2 columnas):\n", transposed, "\n")

# Swapaxes: intercambiar ejes 0 y 1 (equivalente a transpose en 2D)
swapped = np.swapaxes(matrix_2d, 0, 1)
print("Swapaxes (ejes 0 y 1 intercambiados):\n", swapped, "\n")

Matriz 2D original (2 filas x 10 columnas):
 [[2.18543053e+02 4.77821438e+02 3.79397274e+02 3.19396318e+02
  1.20208388e+02 1.20197534e+02 7.61376255e+01 4.39779266e+02
  3.20501755e+02 3.68632660e+02 5.92630224e+01 4.86459433e+02
  4.24599188e+02 1.45552600e+02 1.31821235e+02 1.32532029e+02
  1.86909009e+02 2.86140394e+02 2.44375258e+02 1.81053113e+02
  3.25333803e+02 1.12772237e+02 1.81465092e+02 2.14862829e+02
  2.55231493e+02 4.03329183e+02 1.39853202e+02 2.81405497e+02
  3.16586556e+02 7.09026857e+01 3.23395183e+02 1.26735856e+02
  7.92732168e+01 4.76998492e+02 4.84534415e+02 4.13778807e+02
  1.87076196e+02 9.39524513e+01 3.57904862e+02 2.48068622e+02
  1.04917206e+02 2.72829610e+02 6.54748345e+01 4.59194181e+02
  1.66450992e+02 3.48135028e+02 1.90269984e+02 2.84030610e+02
  2.96019626e+02 1.33184505e+02 4.86313082e+02 3.98809771e+02
  4.72774524e+02 4.52672308e+02 3.19054990e+02 4.64843406e+02
  8.98216259e+01 1.38192288e+02 7.03522800e+01 1.96398649e+02
  2.24904780e+02 1.721070

In [16]:
# -------------------------------
# Ejemplo 3D para moveaxis
# -------------------------------

# Crear un array 3D a partir de una matriz 2D
# matrix_2d tiene shape (2,10)
# Creamos 2 "capas": la original y la original + 1000
matrix_3d = np.array([matrix_2d, matrix_2d + 1000])  # shape (2, 2, 10)
print("Matriz 3D original (2 capas x 2 filas x 10 columnas):\n", matrix_3d, "\n")

# np.moveaxis: mueve el eje especificado a otra posición
# Aquí movemos el eje 0 (capas) al eje 2 (columnas)
# Antes: (capas=2, filas=2, columnas=10)
# Después: (filas=2, columnas=10, capas=2)
moved = np.moveaxis(matrix_3d, 0, 2)
print("Moveaxis (eje 0 movido a eje 2) - shape:", moved.shape, "\n")
print(moved, "\n")


Matriz 3D original (2 capas x 2 filas x 10 columnas):
 [[[2.18543053e+02 4.77821438e+02 3.79397274e+02 3.19396318e+02
   1.20208388e+02 1.20197534e+02 7.61376255e+01 4.39779266e+02
   3.20501755e+02 3.68632660e+02 5.92630224e+01 4.86459433e+02
   4.24599188e+02 1.45552600e+02 1.31821235e+02 1.32532029e+02
   1.86909009e+02 2.86140394e+02 2.44375258e+02 1.81053113e+02
   3.25333803e+02 1.12772237e+02 1.81465092e+02 2.14862829e+02
   2.55231493e+02 4.03329183e+02 1.39853202e+02 2.81405497e+02
   3.16586556e+02 7.09026857e+01 3.23395183e+02 1.26735856e+02
   7.92732168e+01 4.76998492e+02 4.84534415e+02 4.13778807e+02
   1.87076196e+02 9.39524513e+01 3.57904862e+02 2.48068622e+02
   1.04917206e+02 2.72829610e+02 6.54748345e+01 4.59194181e+02
   1.66450992e+02 3.48135028e+02 1.90269984e+02 2.84030610e+02
   2.96019626e+02 1.33184505e+02 4.86313082e+02 3.98809771e+02
   4.72774524e+02 4.52672308e+02 3.19054990e+02 4.64843406e+02
   8.98216259e+01 1.38192288e+02 7.03522800e+01 1.96398649e+02


In [17]:
# -------------------------------
# Manipulación avanzada de arrays: concatenate, stack, split, tile, repeat
# -------------------------------

# Concatenar arrays: une arr_precio y arr_volumen en un solo array 1D
concatenated = np.concatenate([arr_precio, arr_volumen])
print("Array concatenado (1D):\n", concatenated)

Array concatenado (1D):
 [2.18543053e+02 4.77821438e+02 3.79397274e+02 3.19396318e+02
 1.20208388e+02 1.20197534e+02 7.61376255e+01 4.39779266e+02
 3.20501755e+02 3.68632660e+02 5.92630224e+01 4.86459433e+02
 4.24599188e+02 1.45552600e+02 1.31821235e+02 1.32532029e+02
 1.86909009e+02 2.86140394e+02 2.44375258e+02 1.81053113e+02
 3.25333803e+02 1.12772237e+02 1.81465092e+02 2.14862829e+02
 2.55231493e+02 4.03329183e+02 1.39853202e+02 2.81405497e+02
 3.16586556e+02 7.09026857e+01 3.23395183e+02 1.26735856e+02
 7.92732168e+01 4.76998492e+02 4.84534415e+02 4.13778807e+02
 1.87076196e+02 9.39524513e+01 3.57904862e+02 2.48068622e+02
 1.04917206e+02 2.72829610e+02 6.54748345e+01 4.59194181e+02
 1.66450992e+02 3.48135028e+02 1.90269984e+02 2.84030610e+02
 2.96019626e+02 1.33184505e+02 4.86313082e+02 3.98809771e+02
 4.72774524e+02 4.52672308e+02 3.19054990e+02 4.64843406e+02
 8.98216259e+01 1.38192288e+02 7.03522800e+01 1.96398649e+02
 2.24904780e+02 1.72107064e+02 4.22931879e+02 2.10538997e+02

In [18]:
# Stack vertical: apila arrays como filas de una nueva matriz 2D
stacked_v = np.vstack([arr_precio, arr_volumen])
print("\nStack vertical (vstack, filas):\n", stacked_v)


Stack vertical (vstack, filas):
 [[2.18543053e+02 4.77821438e+02 3.79397274e+02 3.19396318e+02
  1.20208388e+02 1.20197534e+02 7.61376255e+01 4.39779266e+02
  3.20501755e+02 3.68632660e+02 5.92630224e+01 4.86459433e+02
  4.24599188e+02 1.45552600e+02 1.31821235e+02 1.32532029e+02
  1.86909009e+02 2.86140394e+02 2.44375258e+02 1.81053113e+02
  3.25333803e+02 1.12772237e+02 1.81465092e+02 2.14862829e+02
  2.55231493e+02 4.03329183e+02 1.39853202e+02 2.81405497e+02
  3.16586556e+02 7.09026857e+01 3.23395183e+02 1.26735856e+02
  7.92732168e+01 4.76998492e+02 4.84534415e+02 4.13778807e+02
  1.87076196e+02 9.39524513e+01 3.57904862e+02 2.48068622e+02
  1.04917206e+02 2.72829610e+02 6.54748345e+01 4.59194181e+02
  1.66450992e+02 3.48135028e+02 1.90269984e+02 2.84030610e+02
  2.96019626e+02 1.33184505e+02 4.86313082e+02 3.98809771e+02
  4.72774524e+02 4.52672308e+02 3.19054990e+02 4.64843406e+02
  8.98216259e+01 1.38192288e+02 7.03522800e+01 1.96398649e+02
  2.24904780e+02 1.72107064e+02 4.22

In [19]:
# Stack horizontal: apila arrays como columnas de una nueva matriz 2D
stacked_h = np.hstack([arr_precio, arr_volumen])
print("\nStack horizontal (hstack, columnas):\n", stacked_h)


Stack horizontal (hstack, columnas):
 [2.18543053e+02 4.77821438e+02 3.79397274e+02 3.19396318e+02
 1.20208388e+02 1.20197534e+02 7.61376255e+01 4.39779266e+02
 3.20501755e+02 3.68632660e+02 5.92630224e+01 4.86459433e+02
 4.24599188e+02 1.45552600e+02 1.31821235e+02 1.32532029e+02
 1.86909009e+02 2.86140394e+02 2.44375258e+02 1.81053113e+02
 3.25333803e+02 1.12772237e+02 1.81465092e+02 2.14862829e+02
 2.55231493e+02 4.03329183e+02 1.39853202e+02 2.81405497e+02
 3.16586556e+02 7.09026857e+01 3.23395183e+02 1.26735856e+02
 7.92732168e+01 4.76998492e+02 4.84534415e+02 4.13778807e+02
 1.87076196e+02 9.39524513e+01 3.57904862e+02 2.48068622e+02
 1.04917206e+02 2.72829610e+02 6.54748345e+01 4.59194181e+02
 1.66450992e+02 3.48135028e+02 1.90269984e+02 2.84030610e+02
 2.96019626e+02 1.33184505e+02 4.86313082e+02 3.98809771e+02
 4.72774524e+02 4.52672308e+02 3.19054990e+02 4.64843406e+02
 8.98216259e+01 1.38192288e+02 7.03522800e+01 1.96398649e+02
 2.24904780e+02 1.72107064e+02 4.22931879e+02 

In [20]:
# Split: divide arr_precio en 2 partes iguales (lista de arrays)
split_array = np.split(arr_precio, 2)
print("\nArray dividido en 2 partes:")
for i, part in enumerate(split_array, start=1):
    print(f"Parte {i}:", part)


Array dividido en 2 partes:
Parte 1: [218.54305348 477.82143788 379.39727382 319.39631789 120.2083882
 120.19753415  76.13762548 439.7792656  320.50175528 368.63266001
  59.26302243 486.45943347 424.59918836 145.55259981 131.82123524
 132.53202943 186.90900933 286.14039423 244.37525839 181.05311309
 325.33380263 112.77223729 181.46509184 214.86282948 255.2314929
 403.32918263 139.85320197 281.40549729 316.58655599  70.90268572
 323.39518336 126.73585566  79.27321684 476.99849176 484.53441488
 413.77880665 187.07619613  93.9524513  357.90486193 248.06862218
 104.91720568 272.82960955  65.4748345  459.19418094 166.45099172
 348.13502796 190.26998424 284.03060953 296.0196257  133.18450499]
Parte 2: [486.31308249 398.80977051 472.7745237  452.67230769 319.05499046
 464.84340576  89.82162592 138.19228809  70.35228001 196.39864884
 224.90478036 172.1070643  422.93187912 210.53899701 176.42052936
 294.21323742 113.41590124 410.98864134  83.54778966 494.09912147
 397.51014618 139.42205669  52

In [21]:
# Tile: repite la secuencia completa de arr_precio 2 veces
tiled_array = np.tile(arr_precio, 2)
print("\nArray con secuencia repetida (tile 2 veces):\n", tiled_array)


Array con secuencia repetida (tile 2 veces):
 [218.54305348 477.82143788 379.39727382 319.39631789 120.2083882
 120.19753415  76.13762548 439.7792656  320.50175528 368.63266001
  59.26302243 486.45943347 424.59918836 145.55259981 131.82123524
 132.53202943 186.90900933 286.14039423 244.37525839 181.05311309
 325.33380263 112.77223729 181.46509184 214.86282948 255.2314929
 403.32918263 139.85320197 281.40549729 316.58655599  70.90268572
 323.39518336 126.73585566  79.27321684 476.99849176 484.53441488
 413.77880665 187.07619613  93.9524513  357.90486193 248.06862218
 104.91720568 272.82960955  65.4748345  459.19418094 166.45099172
 348.13502796 190.26998424 284.03060953 296.0196257  133.18450499
 486.31308249 398.80977051 472.7745237  452.67230769 319.05499046
 464.84340576  89.82162592 138.19228809  70.35228001 196.39864884
 224.90478036 172.1070643  422.93187912 210.53899701 176.42052936
 294.21323742 113.41590124 410.98864134  83.54778966 494.09912147
 397.51014618 139.42205669  52.

In [22]:
# Repeat: repite **cada elemento** de arr_precio 2 veces
repeated_array = np.repeat(arr_precio, 2)
print("\nArray con cada elemento repetido 2 veces (repeat):\n", repeated_array)



Array con cada elemento repetido 2 veces (repeat):
 [218.54305348 218.54305348 477.82143788 477.82143788 379.39727382
 379.39727382 319.39631789 319.39631789 120.2083882  120.2083882
 120.19753415 120.19753415  76.13762548  76.13762548 439.7792656
 439.7792656  320.50175528 320.50175528 368.63266001 368.63266001
  59.26302243  59.26302243 486.45943347 486.45943347 424.59918836
 424.59918836 145.55259981 145.55259981 131.82123524 131.82123524
 132.53202943 132.53202943 186.90900933 186.90900933 286.14039423
 286.14039423 244.37525839 244.37525839 181.05311309 181.05311309
 325.33380263 325.33380263 112.77223729 112.77223729 181.46509184
 181.46509184 214.86282948 214.86282948 255.2314929  255.2314929
 403.32918263 403.32918263 139.85320197 139.85320197 281.40549729
 281.40549729 316.58655599 316.58655599  70.90268572  70.90268572
 323.39518336 323.39518336 126.73585566 126.73585566  79.27321684
  79.27321684 476.99849176 476.99849176 484.53441488 484.53441488
 413.77880665 413.77880665

In [23]:
# -------------------------------
# Estadísticas descriptivas
# -------------------------------

# Media
media_precio = np.mean(df["Precio_Accion"])
# Mediana
mediana_retorno = np.median(df["Retorno"])
# Desviación estándar
std_riesgo = np.std(df["Riesgo"])

# Mostrar resultados de manera clara
print(f"Media del Precio de la Acción: {media_precio:.2f}")
print(f"Mediana del Retorno: {mediana_retorno:.4f}")
print(f"Desviación estándar del Riesgo: {std_riesgo:.4f}")

Media del Precio de la Acción: 261.58
Mediana del Retorno: 0.0100
Desviación estándar del Riesgo: 0.0849


In [24]:
# Resumen rápido de varias estadísticas usando numpy
estadisticas = {
    "Media_Precio": np.mean(df["Precio_Accion"]),
    "Mediana_Retorno": np.median(df["Retorno"]),
    "Std_Riesgo": np.std(df["Riesgo"]),
    "Mínimo_Precio": np.min(df["Precio_Accion"]),
    "Máximo_Precio": np.max(df["Precio_Accion"])
}

print("\nResumen estadístico:")
for k, v in estadisticas.items():
    print(f"{k}: {v:.4f}")



Resumen estadístico:
Media_Precio: 261.5813
Mediana_Retorno: 0.0100
Std_Riesgo: 0.0849
Mínimo_Precio: 52.4850
Máximo_Precio: 494.0991


In [25]:
# -------------------------------
# Funciones matemáticas aplicadas al DataFrame
# -------------------------------

# Logaritmo natural del Precio de la Acción
df["Log_Precio"] = np.log(df["Precio_Accion"])
# Exponencial del Retorno
df["Exp_Retorno"] = np.exp(df["Retorno"])
# Raíz cuadrada del Volumen
df["Sqrt_Volumen"] = np.sqrt(df["Volumen"])

# Mostrar las primeras filas para verificar
print(df[["Precio_Accion", "Log_Precio", "Retorno", "Exp_Retorno", "Volumen", "Sqrt_Volumen"]].head())


   Precio_Accion  Log_Precio   Retorno  Exp_Retorno  Volumen  Sqrt_Volumen
0     218.543053    5.386983  0.004983     1.004995    51015    225.865004
1     477.821438    6.169237 -0.025174     0.975140    55268    235.091472
2     379.397274    5.938584 -0.077533     0.925396    88939    298.226424
3     319.396318    5.766433  0.003428     1.003434    19141    138.351003
4     120.208388    4.789227 -0.053115     0.948271    81356    285.229732


In [26]:
# -------------------------------
# Funciones trigonométricas aplicadas al DataFrame
# -------------------------------

# Seno del Beta
df["Sin_Beta"] = np.sin(df["Beta"])
# Coseno del Beta
df["Cos_Beta"] = np.cos(df["Beta"])

# Mostrar las primeras filas para verificar
print(df[["Beta", "Sin_Beta", "Cos_Beta"]].head())

       Beta  Sin_Beta  Cos_Beta
0  1.486001  0.996407  0.084694
1  1.253378  0.950044  0.312115
2  0.876260  0.768350  0.640030
3  0.583501  0.550949  0.834539
4  1.277147  0.957194  0.289447


In [27]:
# -------------------------------
# Operaciones sobre arrays aplicadas al DataFrame
# -------------------------------

# Suma acumulativa de Dividendos
df["Cumsum_Dividendos"] = np.cumsum(df["Dividendos"])

# Diferencias entre precios consecutivos de la acción
df["Diff_Precio"] = np.diff(df["Precio_Accion"], prepend=df["Precio_Accion"].iloc[0])

# Redondeo del Ratio Precio/Utilidad a 2 decimales
df["Ratio_P_E_Round"] = np.round(df["Ratio_P_E"], 2)

# Mostrar las primeras filas para verificar
print(df[["Dividendos", "Cumsum_Dividendos", "Precio_Accion", "Diff_Precio", "Ratio_P_E", "Ratio_P_E_Round"]].head())


   Dividendos  Cumsum_Dividendos  Precio_Accion  Diff_Precio  Ratio_P_E  \
0        0.00               0.00     218.543053     0.000000   8.974516   
1        0.03               0.03     477.821438   259.278384  28.505062   
2        0.00               0.03     379.397274   -98.424164  23.210770   
3        0.02               0.05     319.396318   -60.000956  32.031144   
4        0.00               0.05     120.208388  -199.187930  23.205723   

   Ratio_P_E_Round  
0             8.97  
1            28.51  
2            23.21  
3            32.03  
4            23.21  


In [28]:
# -------------------------------
# Operaciones lógicas y condicionales
# -------------------------------

# Crear columna booleana indicando si el Volumen es alto (>50,000)
df["Alta_Volumen"] = df["Volumen"] > 50000

# Crear columna categórica según el Retorno
df["Estado_Retorno"] = np.where(df["Retorno"] > 0.02, "Ganancia", "Perdida")

# Mostrar las primeras filas para verificar
print(df[["Volumen", "Alta_Volumen", "Retorno", "Estado_Retorno"]].head())


   Volumen  Alta_Volumen   Retorno Estado_Retorno
0    51015          True  0.004983        Perdida
1    55268          True -0.025174        Perdida
2    88939          True -0.077533        Perdida
3    19141         False  0.003428        Perdida
4    81356          True -0.053115        Perdida


In [29]:
# -------------------------------
# Transformaciones matemáticas avanzadas
# -------------------------------

# Redondear Riesgo a 2 decimales
df["Riesgo_Round"] = np.round(df["Riesgo"], 2)

# Piso y techo de Riesgo
df["Riesgo_Floor"] = np.floor(df["Riesgo"])
df["Riesgo_Ceil"] = np.ceil(df["Riesgo"])

# Valor absoluto del Retorno
df["Retorno_Abs"] = np.abs(df["Retorno"])

# Raíz cuadrada del Volumen (asegurando valores positivos)
df["Sqrt_Volumen"] = np.sqrt(df["Volumen"].clip(lower=0))

# Mostrar las primeras filas para verificar
print(df[["Riesgo", "Riesgo_Round", "Riesgo_Floor", "Riesgo_Ceil", "Retorno", "Retorno_Abs", "Volumen", "Sqrt_Volumen"]].head())


     Riesgo  Riesgo_Round  Riesgo_Floor  Riesgo_Ceil   Retorno  Retorno_Abs  \
0  0.233298          0.23           0.0          1.0  0.004983     0.004983   
1  0.072588          0.07           0.0          1.0 -0.025174     0.025174   
2  0.190638          0.19           0.0          1.0 -0.077533     0.077533   
3  0.034751          0.03           0.0          1.0  0.003428     0.003428   
4  0.024988          0.02           0.0          1.0 -0.053115     0.053115   

   Volumen  Sqrt_Volumen  
0    51015    225.865004  
1    55268    235.091472  
2    88939    298.226424  
3    19141    138.351003  
4    81356    285.229732  


In [30]:
# -------------------------------
# Operaciones matriciales y álgebra lineal
# -------------------------------

# Convertir columnas seleccionadas en matriz NumPy
matriz_precios = df[["Precio_Accion", "Beta", "Ratio_P_E"]].values

In [31]:
# Producto matricial (X^T * X)
producto = np.dot(matriz_precios.T, matriz_precios)
print("Producto matricial (X^T * X):\n", producto)

Producto matricial (X^T * X):
 [[8.61668220e+06 2.77107766e+04 5.21890526e+05]
 [2.77107766e+04 1.22534398e+02 2.11760076e+03]
 [5.21890526e+05 2.11760076e+03 4.98952546e+04]]


In [32]:
# Determinante con pequeña regularización para evitar singularidades
determinante = np.linalg.det(producto + np.eye(producto.shape[0]) * 1e-6)
print("\nDeterminante con regularización:", determinante)


Determinante con regularización: 3603059066600.503


In [33]:
# -------------------------------
# Eigenvalores y eigenvectores con explicación
# -------------------------------

# Calcular eigenvalores y eigenvectores de la matriz 'producto' (X^T * X)
# Eigenvalores (λ): indican la cantidad de varianza explicada por cada componente principal.
#                  Valores más grandes = más importancia de esa dirección en los datos.
# Eigenvectores (v): vectores que indican la dirección de cada componente principal en el espacio de variables.
eigenvalores, eigenvectores = np.linalg.eig(producto)

# Ordenar los eigenvalores de mayor a menor para identificar las componentes más importantes
orden = np.argsort(eigenvalores)[::-1]  # argsort devuelve los índices que ordenan el array
eigenvalores_ordenados = eigenvalores[orden]  # Eigenvalores ordenados
eigenvectores_ordenados = eigenvectores[:, orden]  # Reorganizar columnas de eigenvectores según el orden

# Mostrar eigenvalores de manera legible con 4 decimales
print("\nEigenvalores ordenados de mayor a menor:")
for i, val in enumerate(eigenvalores_ordenados, start=1):
    print(f"λ{i}: {val:.4f}  # Varianza explicada por esta componente")

# Mostrar eigenvectores correspondientes a cada eigenvalor
print("\nEigenvectores correspondientes (columnas representan vectores):")
for i in range(eigenvectores_ordenados.shape[1]):
    # Cada columna del eigenvector corresponde a la dirección principal de la varianza de los datos
    print(f"v{i+1}: {eigenvectores_ordenados[:, i]}")



Eigenvalores ordenados de mayor a menor:
λ1: 8648448.0420  # Varianza explicada por esta componente
λ2: 18229.0906  # Varianza explicada por esta componente
λ3: 22.8543  # Varianza explicada por esta componente

Eigenvectores correspondientes (columnas representan vectores):
v1: [0.99815792 0.00321311 0.06058414]
v2: [ 0.06064379 -0.02389251 -0.99787348]
v3: [ 0.00175877 -0.99970937  0.02404335]
